import { App } from './js/core/app-state.ts';

import init_01_start from './js/core/01_start.ts';
import init_02_three_scene from "./js/core/02_three_scene.ts";
import init_03_model_load_gltf_vrm from './js/core/03_model_load_gltf_vrm.ts';
import init_04_bg_load from './js/character/04_bg_load.ts';
import init_05_move_mode from './js/core/05_move_mode.ts';
import init_06_fpv_mode from './js/character/06_fpv_mode.ts';
import init_07_click_interact from "./js/character/07_click_interact.ts";
import init_08b_expression_engine from './js/character/08_expression_engine.ts';
import init_09_emotion_controller from './js/character/09_emotion_controller.ts';
import init_09b_motion_blender from './js/character/09b_motion_blender.ts';
import init_09c_mixamo_retarget from './js/character/09c_mixamo_retarget.ts';
import init_09d_mixamo_library_loader from './js/character/09d_mixamo_library_loader.ts';
import init_09e_mixamo_emotion_bridge from './js/character/09e_mixamo_emotion_bridge.ts';
import init_08_state_switch from './js/core/08_state_switch.ts';
import init_09_websocket from './js/network/09_websocket.ts';
import init_10_tts_lipsync from './js/core/10_tts_lipsync.ts';
import init_11_voice_record from './js/audio/11_voice_record.ts';
import init_12_vad_auto from './js/core/12_vad_auto.ts';
import init_13_messages from './js/ui/13_messages.ts';
import init_14_toast from './js/ui/14_toast.ts';
import init_15_model_ui from './js/ui/15_model_ui.ts';
import init_16_bg_ui from './js/ui/16_bg_ui.ts';
import init_17_events from './js/ui/17_events.ts';
import init_18_tts_settings from './js/audio/18_tts_settings.ts';
import init_19_boot from './js/core/19_boot.ts';
import init_20_bgm_player from './js/audio/20_bgm_player.ts';
import init_28_music_ui from './js/audio/28_music_ui.ts';
import init_29_video_ui from './js/audio/29_video_ui.ts';
import init_32_workspace_ui from './js/audio/32_workspace_ui.ts';
import init_22_game_mode from "./js/game/init-game-mode.ts";
import init_23_name_settings from './js/ui/23_name_settings.ts';
import init_24_footstep_sfx from './js/audio/24_footstep_sfx.ts';
import init_25_character_cards from "./js/ui/25_character_cards.ts";
import init_25b_llm_providers from "./js/ui/26_llm_providers.ts";
import init_26_webxr_vr from "./js/vr/webxr-vr.ts";
import init_27_wake_word from './js/audio/26_wake_word.ts';
import init_28_codex_runner from "./js/codex/28_codex_runner.ts";
import init_29_task_center from './js/ui/27_task_center.ts';
import init_30_task_tree from './js/ui/30_task_tree.ts';
import init_30_task_big_screen from "./js/ui/30_task_big_screen.ts";
import init_31_tool_chain from './js/ui/31_tool_chain.ts';
import init_32_vr_hud from './js/vr/vr-hud.ts';

init_01_start(App);
init_02_three_scene(App);
init_03_model_load_gltf_vrm(App);
init_04_bg_load(App);
init_05_move_mode(App);
init_06_fpv_mode(App);
init_07_click_interact(App);
init_08b_expression_engine(App);
init_09_emotion_controller(App);
init_09b_motion_blender(App);
init_09c_mixamo_retarget(App);
init_09d_mixamo_library_loader(App);
init_09e_mixamo_emotion_bridge(App);
init_08_state_switch(App);
init_09_websocket(App);
init_10_tts_lipsync(App);
init_11_voice_record(App);
init_12_vad_auto(App);
init_13_messages(App);
init_14_toast(App);
init_15_model_ui(App);
init_16_bg_ui(App);
init_17_events(App);
init_18_tts_settings(App);
init_19_boot(App);
init_20_bgm_player(App);
init_28_music_ui(App);
init_29_video_ui(App);
init_32_workspace_ui(App);
init_22_game_mode(App);
init_23_name_settings(App);
init_24_footstep_sfx(App);
init_25_character_cards(App);
init_25b_llm_providers(App);
init_26_webxr_vr(App);
init_27_wake_word(App);
init_28_codex_runner(App);
init_29_task_center(App);
init_30_task_tree(App);
init_30_task_big_screen(App);
init_31_tool_chain(App);
init_32_vr_hud(App);

// DEBUG expose
Object.defineProperty(window, '_App', { get: () => App });
Object.defineProperty(window, '_GameManager', { get: () => window._gameManager });
Object.defineProperty(window, '_expressionRL', { get: () => App._expressionRL });
Object.defineProperty(window, '_motionLib', { get: () => App.MOTION_LIBRARY });
Object.defineProperty(window, '_mixamoLib', { get: () => App.mixamoClips });
Object.defineProperty(window, '_animLib', { get: () => ({ config: App._animLibraryConfig, stats: App.getAnimLibraryStats() }) });